# Generated by Django 5.2.1 on 2025-05-24 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('var_type', models.CharField(choices=[('input', 'Entrada'), ('output', 'Salida')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('func_type', models.CharField(choices=[('triangular', 'Triangular'), ('trapezoidal', 'Trapezoidal'), ('gaussian', 'Gaussiana'), ('singleton', 'Singleton')], max_length=20)),
                ('parameters', models.JSONField(help_text='Parámetros: ej. [a, b, c] para triangular')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_functions', to='sistema_fuzzy.variable')),
            ],
        ),
    ]
